### ISSUE TITLE
Compatibility with third party blocklists

### ISSUE THREAD

**Issue by gunnersson** [RequestPolicyContinued/subscriptions#28]
Dear all,

before using RPC, I have been trying and actually using AdBlock and several derivates and forks and the likes. Also trying and actually using several hosts file subscriptions.

Most of the hosts file subscriptions have been working well for me. But I have been experiencing problems with several subscriptions of AdBlock rule sets. Some of those rules destroyed parts of some of my visited sites. Not always easy to identify...

What about taking the common hosts files, merging them (just unique entries in the final file) and then including it to RPC? Looking at URLs and explicitly allowing or denying them is what RPC does, isn't it.

Here are some hosts files I could suggest:
https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
http://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts
http://winhelp2002.mvps.org/hosts.txt
http://www.malwaredomainlist.com/hostslist/hosts.txt

Cheers,

Gunner

**Comment by gunnersson** [comment]
adding these (selection needed):
http://someonewhocares.org/hosts/
http://hosts-file.net/?s=Download

**Comment by nodiscc** [comment]
Thank you for referencing these lists; I had imported Peter Lowe's Ad Server list (pgl.yoyo.org) in https://github.com/RequestPolicyContinued/subscriptions/commit/994ba7dd3835f3123416eef26eafc6b2fb04fb13.

I'm ok with importing these lists to subscriptions; (and create a script to update them periodically?) 

However I think we _should_ import these as new subscriptions files (labeled Simple Malware, etc) Yes it should have been done with Peter Lowe's list.

Another thing, wouldn't it be simpler to just recommend an Ad Blocker (uBlock origin) and these lists? What does RP do differently than uBlock regarding blocklists (filtering method, performance, etc) (it was also asked at the time if RP's performance would decrease with large lists)

@myrdd what do you think?

**Comment by gunnersson** [comment]
Well, when using an AdBlock derivate, it has been uBlock_0 for my best experience:
https://github.com/gorhill/uBlock

Just  recently I have been comparing uBlock_0 and RPC for my needs... 

Question to you proficient guys: by using uBlock_0 with only hosts file subscriptions (hosts files mentioned before) but no other AdBlock rule sets (with special AdBlock expressions), what would be the difference between this solution and RPC use? Where would be advantages/disadvantages of either solution?

Thank you,

Gunner

**Comment by myrdd** [comment]
Hi @gunnersson, thank you for your suggestions, I appreciate you would like to see those lists merged. However, I think it might not be the time yet to do that.

To be more specific, currently the list of available subscriptions is hard-coded in the addon itself. It's not trivial to add new lists from the *subscriptions* repo's point of view. I would say, before we merge big lists, that issue should be fixed – see https://github.com/RequestPolicyContinued/requestpolicy/issues/678.

---

> I have been experiencing problems with several subscriptions of AdBlock rule sets. Some of those rules destroyed parts of some of my visited sites. Not always easy to identify...

It would help if the RequestPolicy menu would show which subscriptions are used on a specific site. It's not implemented yet. See https://github.com/RequestPolicyContinued/requestpolicy/issues/660. It's not likely that I'll be implementing it before the `1.0` version milestone.

> Looking at URLs and explicitly allowing or denying them is what RPC does, isn't it.

If you mean the *addon*, yes. RequestPolicy in most cases looks at the *hostname* part of the URL, but also Scheme and Port. The path can be part of a rule as well, but I've never tested that feature yet, and there's no user interface for it.

> I'm ok with importing these lists to subscriptions; (and create a script to update them periodically?)

Yes, I think periodic updates would be nice.

> I think we should import these as new subscriptions files (labeled Simple Malware, etc)

I agree @nodiscc. Another reason for fixing https://github.com/RequestPolicyContinued/requestpolicy/issues/678.

> What does RP do differently than uBlock regarding blocklists (filtering method, performance, etc) (it was also asked at the time if RP's performance would decrease with large lists)

I've not tested performance yet, that's why I've said that.

> Question to you proficient guys: by using uBlock_0 with only hosts file subscriptions (hosts files mentioned before) but no other AdBlock rule sets (with special AdBlock expressions), what would be the difference between this solution and RPC use? Where would be advantages/disadvantages of either solution?

@gunnersson You can run as many filters as you want. It *might* impact performance. If *one* of those addons blocks a request, the request will be blocked. But, maybe multiple addons are blocking the same request, and you want to allow the request, then you have to allow it in each addon, which is bad user experience. Best if you try it out yourself.

> Another thing, wouldn't it be simpler to just recommend an Ad Blocker (uBlock origin) and these lists?

@nodiscc as long as we don't have the lists in RPC, I don't see any problem in pointing to uBlock if someone wants to use the lists.

**Comment by nodiscc** [comment]
- [ ] import https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
 - [ ] import https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
 - [ ] import https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
 - [ ] import http://pgl.yoyo.org/adservers/serverlist.php?showintro=0;hostformat=hosts
 - [ ] import http://winhelp2002.mvps.org/hosts.txt
 - [ ] import http://www.malwaredomainlist.com/hostslist/hosts.txt
 - [ ] automate updating/importing lists from upstream (makefile)
 - [ ] benchmark performance difference between no subscriptions/all subscription loaded
 - [ ] recommend an ad blocker in documentation?

**Comment by gunnersson** [comment]
Appreciated.

Currently, I use uBlock_0 with *no* AdBlock specific rules but hosts files rules only. Therefore, these ones are included and work well and properly:

https://s3.amazonaws.com/lists.disconnect.me/simple_malware.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_malvertising.txt
https://s3.amazonaws.com/lists.disconnect.me/simple_tracking.txt
http://pgl.yoyo.org/adservers/serverlist.php?hostformat=hosts&showintro=1&mimetype=plaintext
http://winhelp2002.mvps.org/hosts.htm
http://www.malwaredomainlist.com/hostslist/hosts.txt
http://someonewhocares.org/hosts/
http://hosts-file.net/?s=Download

So,
http://someonewhocares.org/hosts/
http://hosts-file.net/?s=Download
are additional.

But be aware and pay care:
http://hosts-file.net/?s=Download is not *one* TXT file. There are offered many. They are categorized (like malware, ads, trackers, etc.). But looks promising.

**Comment by nodiscc** [comment]
See https://github.com/RequestPolicyContinued/subscriptions/pull/55
